### ISSUE TITLE
Unable to install deb package version 1.3.1 

### ISSUE THREAD

**Issue by skwasniak** [OWASP/threat-dragon-desktop#90]
System:
```
$lscpu
Architecture:                    x86_64

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

dpkg output:
```
$ sudo dpkg -i threatdragon-1.3.1.x86_64.deb

dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 5 package 'threatdragon:x86_64':
 'x86_64' is not a valid architecture name in 'Architecture' field: character '_' not allowed (only letters, digits and characters '-')
dpkg: error processing archive threatdragon-1.3.1.x86_64.deb (--install):
 package architecture (x86_64) does not match system (amd64)
Errors were encountered while processing:
 threatdragon-1.3.1.x86_64.deb
 ```

**Comment by jgadsden** [comment]
Hello @skwasniak - thanks for trying this out.

Could you try the "threatdragon-1.3.1.amd64.deb" ? This is worth trying because my trisquel Linux identifies my cpu as x86_64 when in fact it is AMD64, and your Linux box may be the same.

If neither version works then there is definitely a problem, and worse is I do not have a true x86_64 linux machine

**Comment by skwasniak** [comment]
Hi, PC I'm using is HP EliteBook 840 G6 so `Intel Whiskey Lake` processor, but it works with the AMD package though, so thank you.

Just a side note - there is a warning about the `_` in the architecture name.
