### ISSUE TITLE
"print report" doesn't work

### ISSUE THREAD

**Issue by sherbo** [OWASP/threat-dragon-desktop#95]
**Describe the bug**
Clicking "Print" on the Demo report results in a red "Report printing failed" modal and nothing happens.

**Expected behavior**
Clicking "Print" on the Demo report should bring up a screen to print the document.

**Environment**
 - Version: 1.4.0
 - Platform: Desktop
 - OS: MacOS 10.15.7
 
**To Reproduce**
1. Open Demo model
2. Click "Report"
2. Click "Print"

**Any additional context, screenshots, etc**

**Comment by jgadsden** [comment]
Hello @sherbo - thanks again for another good bug report. I can not print (except to PDF) for any of my models using version 1.4.0 .

This used to work OK, I will go back in the releases to find where it stopped working

**Comment by jgadsden** [comment]
Hello @sherbo I found that it was because no printer was available for printing, and so Threat Dragon throws an error.

It is not informative though, it looks as though Threat Dragon has failed, so I have increased the information when this error is displayed.

Could you check that you have a printer available? And that you still get this error when a printer is available for sure?
Thanks again for finding this.

**Comment by jgadsden** [comment]
This problem may be deeper than at first thought - I can not print even though I have a printer attached.
@sherbo could you confirm that print does not work even though you have  a printer available?
Many thanks again
